/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "ResourcePackConverter"
include(":Console")
include(":Applications")
include(":Gui")
include(":conversions")
include(":Forwards")
include(":Library")
project(":Console").projectDir = file("Applications/Console")
project(":Gui").projectDir = file("Applications/Gui")
project(":Forwards").projectDir = file("conversions/Forwards")
project(":Library").projectDir = file("library")
